name: 'Get or Cache Dependencies'
description: |
  This action checks if the dependencies are already cached. If not, it installs them and caches them for future use.
  This is useful for speeding up the workflow by avoiding unnecessary installations.
inputs:
  caching:
    description: 'Enable or disable caching of dependencies'
    required: false
    default: 'true'
outputs:
  cache-hit:
    description: 'Indicates if the cache was hit or not'
    value: ${{ steps.install.outputs.cache}}
runs:
  using: 'composite'
  steps:
      - name: Cache dependencies
        if: inputs.caching == 'true'
        id: cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        id: install
        if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
        run: |
          npm ci
          echo "Cache='${{inputs.caching}}'">>$GITHUB_OUTPUT
        shell: bash
